### ISSUE TITLE
Codon table

### ISSUE THREAD

**Issue by ascendo** [cathalgarvey/PySplicer#6]
Hello.

I just want to use my own codon table.

Is there any way to change the codon table to JSON format?

My codon table looks like below.

Regards,

Arg AGG 84692 10.560 0.200
Arg CGC 27441 3.420 0.070
Arg AGA 141985 17.710 0.340
Arg CGT 66111 8.240 0.160
Arg CGA 57673 7.190 0.140
Arg CGG 41600 5.190 0.100
Asp GAT 315310 39.320 0.710
Asp GAC 130497 16.270 0.290
Ile ATA 123875 15.450 0.250
Ile ATT 207505 25.880 0.430
Ile ATC 156226 19.480 0.320
Phe TTC 158548 19.770 0.450
Phe TTT 192265 23.980 0.550
Glu GAA 289210 36.070 0.580
Glu GAG 206681 25.770 0.420
--- TAA 7597 0.950 0.380
--- TAG 4314 0.540 0.210
--- TGA 8346 1.040 0.410
Thr ACT 130776 16.310 0.320
Thr ACG 56851 7.090 0.140
Thr ACC 89411 11.150 0.220
Thr ACA 136964 17.080 0.330
Tyr TAC 101486 12.660 0.450
Tyr TAT 125952 15.710 0.550
Ala GCG 56601 7.060 0.120
Ala GCA 157345 19.620 0.340
Ala GCC 88554 11.040 0.190
Ala GCT 167025 20.830 0.360
Gly GGA 186311 23.230 0.370
Gly GGC 68894 8.590 0.140
Gly GGT 161591 20.150 0.320
Gly GGG 85015 10.600 0.170
Pro CCT 123574 15.410 0.340
Pro CCC 51082 6.370 0.140
Pro CCG 58667 7.320 0.160
Pro CCA 131246 16.370 0.360
Cys TGC 64595 8.060 0.430
Cys TGT 85073 10.610 0.570
Met ATG 208518 26.000 1.000
Leu CTC 111788 13.940 0.150
Leu CTG 89776 11.200 0.120
Leu CTA 73328 9.140 0.100
Leu TTA 114511 14.280 0.150
Leu CTT 187233 23.350 0.250
Leu TTG 171675 21.410 0.230
His CAC 67440 8.410 0.340
His CAT 128220 15.990 0.660
Lys AAG 232169 28.950 0.460
Lys AAA 274622 34.250 0.540
Gln CAA 159032 19.830 0.580
Gln CAG 117004 14.590 0.420
Val GTA 87032 10.850 0.170
Val GTG 124709 15.550 0.240
Val GTT 203451 25.370 0.390
Val GTC 102101 12.730 0.200
Asn AAT 248026 30.930 0.640
Asn AAC 139802 17.430 0.360
Ser TCA 156939 19.570 0.210
Ser TCG 78257 9.760 0.110
Ser TCT 198409 24.740 0.270
Ser AGT 117425 14.640 0.160
Ser TCC 110188 13.740 0.150
Ser AGC 73232 9.130 0.100
Trp TGG 97263 12.130 1.000

**Comment by cathalgarvey** [comment]
There's certainly a way, yes! But it's not the way that's packaged with PySplicer. :)

PySplicer can convert tables of [this format](http://www.kazusa.or.jp/codon/cgi-bin/showcodon.cgi?species=105361) (using [this method](https://github.com/cathalgarvey/PySplicer/blob/master/pysplicer/translators.py#L138)), but it seems you have a table of [this format](http://www.kazusa.or.jp/codon/cgi-bin/showcodon.cgi?species=105361&aa=1&style=GCG) instead. Those are the same tables, you can see how they are formatted differently but contain the same information.

I put together a quick notebook to generate a suitable table from yours, [Codon Table Conversion.ipynb.zip](https://github.com/cathalgarvey/PySplicer/files/507940/Codon.Table.Conversion.ipynb.zip). And, here's the output which *should* be importable to the ReverseTranslator:

```json
{
 "C": {
  "TGT": 10.61,
  "TGC": 8.06
 },
 "E": {
  "GAA": 36.07,
  "GAG": 25.77
 },
 "Q": {
  "CAG": 14.59,
  "CAA": 19.83
 },
 "*": {
  "TAA": 0.95,
  "TGA": 1.04,
  "TAG": 0.54
 },
 "I": {
  "ATC": 19.48,
  "ATT": 25.88,
  "ATA": 15.45
 },
 "G": {
  "GGC": 8.59,
  "GGT": 20.15,
  "GGA": 23.23,
  "GGG": 10.6
 },
 "Y": {
  "TAC": 12.66,
  "TAT": 15.71
 },
 "L": {
  "CTC": 13.94,
  "TTG": 21.41,
  "CTG": 11.2,
  "TTA": 14.28,
  "CTT": 23.35,
  "CTA": 9.14
 },
 "D": {
  "GAT": 39.32,
  "GAC": 16.27
 },
 "K": {
  "AAG": 28.95,
  "AAA": 34.25
 },
 "F": {
  "TTC": 19.77,
  "TTT": 23.98
 },
 "T": {
  "ACA": 17.08,
  "ACT": 16.31,
  "ACC": 11.15,
  "ACG": 7.09
 },
 "V": {
  "GTG": 15.55,
  "GTT": 25.37,
  "GTA": 10.85,
  "GTC": 12.73
 },
 "H": {
  "CAT": 15.99,
  "CAC": 8.41
 },
 "A": {
  "GCG": 7.06,
  "GCT": 20.83,
  "GCC": 11.04,
  "GCA": 19.62
 },
 "S": {
  "TCG": 9.76,
  "TCT": 24.74,
  "TCC": 13.74,
  "AGC": 9.13,
  "AGT": 14.64,
  "TCA": 19.57
 },
 "R": {
  "CGG": 5.19,
  "CGT": 8.24,
  "AGA": 17.71,
  "AGG": 10.56,
  "CGC": 3.42,
  "CGA": 7.19
 },
 "W": {
  "TGG": 12.13
 },
 "N": {
  "AAT": 30.93,
  "AAC": 17.43
 },
 "M": {
  "ATG": 26.0
 },
 "P": {
  "CCC": 6.37,
  "CCA": 16.37,
  "CCT": 15.41,
  "CCG": 7.32
 }
}```
